"use client";

import { useSession, signIn, signOut } from "next-auth/react";
import { useState } from "react";

// 型定義
type Post = {
  id: number;
  author: string;
  title: string;
  body: string;
  tag: string;
};

export default function Home() {
  const { data: session, status } = useSession();
  const [openPostId, setOpenPostId] = useState<number | null>(null);

  // 仮のデータ（以前のもの）
  const posts: Post[] = [
    { id: 1, author: "久保田", title: "雨の日の放課後", body: "窓の外は灰色で...", tag: "今週のお題" },
    { id: 2, author: "部員A", title: "無題", body: "プログラミングと文学...", tag: "コラム" },
  ];

  const togglePost = (id: number) => {
    setOpenPostId(openPostId === id ? null : id);
  };

  // 1. ロード中
  if (status === "loading") return <div className="p-10 text-center text-slate-500">読み込み中...</div>;

  // 2. 未ログイン（紹介画面）
  if (!session) {
    return (
      <main className="min-h-screen bg-slate-900 text-white flex flex-col items-center justify-center p-6">
        <h1 className="text-4xl font-serif mb-4 italic text-blue-400">文芸部 Portal</h1>
        <p className="text-slate-400 mb-8 text-center max-w-sm">
          言葉を紡ぎ、共有し、高め合う。
        </p>
        <button 
          onClick={() => signIn("google")}
          className="bg-white text-black px-8 py-3 rounded-full font-bold hover:bg-slate-200 transition"
        >
          Googleでログイン
        </button>
      </main>
    );
  }

  // 3. ログイン済み（メイン画面：ここにトグルなどを戻す！）
  return (
    <main className="min-h-screen bg-white max-w-2xl mx-auto border-x border-slate-200">
      <header className="sticky top-0 bg-white/80 backdrop-blur-md border-b border-slate-200 p-4 flex justify-between items-center z-10">
        <div>
          <h1 className="text-xl font-bold">文芸部ポータル</h1>
          <p className="text-xs text-slate-500">ようこそ、{session.user?.name} さん</p>
        </div>
        <button onClick={() => signOut()} className="text-xs bg-slate-100 px-3 py-1 rounded hover:bg-slate-200">
          ログアウト
        </button>
      </header>

      {/* タイムライン */}
      <div className="divide-y divide-slate-200">
        {posts.map((post) => (
          <article 
            key={post.id} 
            className="p-4 hover:bg-slate-50 cursor-pointer transition"
            onClick={() => togglePost(post.id)}
          >
            <div className="flex items-center gap-2 mb-1">
              <span className="font-bold text-slate-900">{post.author}</span>
              <span className="text-xs bg-slate-100 px-2 py-0.5 rounded text-slate-600">{post.tag}</span>
            </div>
            <h2 className="text-lg font-bold mb-1">{post.title}</h2>
            
            {openPostId === post.id ? (
              <div className="mt-4 p-4 bg-slate-50 rounded-lg border-l-4 border-blue-500 animate-in fade-in slide-in-from-top-1">
                <p className="text-slate-800 whitespace-pre-wrap leading-relaxed">{post.body}</p>
              </div>
            ) : (
              <p className="text-slate-500 line-clamp-1 text-sm">クリックして続きを読む...</p>
            )}
          </article>
        ))}
      </div>

      {/* 投稿ボタン（右下に固定） */}
      <button className="fixed bottom-8 right-[calc(50%-300px)] w-14 h-14 bg-blue-500 text-white rounded-full shadow-lg flex items-center justify-center text-2xl hover:bg-blue-600 transition-transform hover:scale-110">
        ＋
      </button>
    </main>
  );
}


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}


これはいったんけしちゃっていいの？